### ISSUE TITLE
Error getting token interactively

### ISSUE THREAD

**Issue by explaineverything** [microsoftgraph/msgraph-training-ios-objectivec#13]
Hi, I am trying to run example projects in Objective-C and Swift. I am using Microsoft Graph Quick Start tutorial:

[https://developer.microsoft.com/en-us/graph/quick-start](https://developer.microsoft.com/en-us/graph/quick-start)

I made all the steps. When I click Sign In button, I have the following error in both projects: 
Error getting token interactively: Optional(Error Domain=MSALErrorDomain Code=-42708 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to delete broker key with error: -34018})

![IMG_8132](https://user-images.githubusercontent.com/13270450/67519996-4be8d700-f6a8-11e9-9ac3-c95eca4f3dc0.PNG)

As I looked deeper, methods SecItemDelete and SecItemAdd in MSIDBrokerKeyProvider returns error (-34018)

I am running example project on iOS 13.1.3 on iPad Pro. 
Any Ideas? Please help. 

Łukasz

**Comment by jasonjoh** [comment]
Have a look at https://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator. I've not run into this issue myself, but that sounds like it might be your problem.

**Comment by explaineverything** [comment]
OK thanks, I used older version of MSAL (like in tutorial). After updating to newest version, the problem no longer exists.
