### ISSUE TITLE
MSALDeclinedScopesKey  Server returned less scopes than requested

### ISSUE THREAD

**Issue by navee4721** [microsoftgraph/msgraph-training-ios-objectivec#20]
I am using delegated scope api://exmaplestring/allowadmins in scopes along with User.Read and Calendars.Read i am getting error during signing as server returned scopes other than requested leaving the scope api://exmaplestring/allowadmins). I am able to generate token with User.Read and Calendars.Read but not with scope api://exmaplestring/allowadmins.

I assigned permissions correctly

**Comment by jasonjoh** [comment]
@navee4721 you cannot get a single token for both resources. You must make two requests: one for the Graph scopes, and one for the custom scope. You'll have to manage both tokens, using the correct token for the correct API.

This is out of scope for this sample.

**Comment by navee4721** [comment]
@jasonjoh thanks
