### ISSUE TITLE
Signout Issue using msal

### ISSUE THREAD

**Issue by navee4721** [microsoftgraph/msgraph-training-ios-objectivec#23]
I am using MSAL for objc based mobile app. When user initially sign in and click on sign out, he is logging out of app but not killing user session. When user signin next time he is getting into app without any creds. Does msal kills session ? if so whats the method which needs to be called

**Comment by jasonjoh** [comment]
This might be better answered on the [MSAL for Obj-C](https://github.com/AzureAD/microsoft-authentication-library-for-objc) repo's issue list. Are you saying that the method in this sample isn't signing out?

https://github.com/microsoftgraph/msgraph-training-ios-objectivec/blob/7e9a7f64bf3b37b506ad74e3d47e00f7e17b305f/demo/GraphTutorial/GraphTutorial/AuthenticationManager.m#L125-L137

**Comment by navee4721** [comment]
@jasonjoh  Yes jason Signout method just removing the account but not killing the token session. So when user logins for next time , user able to get into application without providing credentials

**Comment by jasonjoh** [comment]
Oh I see. So yeah, the user is still signed in in the browser, so when you login again to the app, you can choose that account there and you don't have to re-enter your password, etc.. Is that what you mean?

Found this in the [MSAL wiki](https://github.com/AzureAD/microsoft-authentication-library-for-objc/tree/master#implement-signout):

> To signout account from your app, call MSAL's signout API. You can also optionally sign out from the browser. When MSAL is running on a shared device, signout API will signout globally from all apps on user's device.

Looks like this would do the trick:

```
MSALAccount *account = ... /* account retrieved above */;
        
MSALSignoutParameters *signoutParameters = [[MSALSignoutParameters alloc] initWithWebviewParameters:webViewParameters];
signoutParameters.signoutFromBrowser = YES;
        
[application signoutWithAccount:account signoutParameters:signoutParameters completionBlock:^(BOOL success, NSError * _Nullable error)
{
	if (!success)
	{
		// Signout failed
		return;
	}
            
	// Sign out completed successfully
}];
```

**Comment by navee4721** [comment]
Yes I will test this scenario thanks

**Comment by jasonjoh** [comment]
No problem. I'm going to close this issue since it's not strictly related to the sample :D. If that code doesn't work for you, I'd suggest opening an issue on the MSAL repo.
