### ISSUE TITLE
Sample app is not working on IOS 13 

### ISSUE THREAD

**Issue by navee4721** [microsoftgraph/msgraph-training-ios-objectivec#24]
Sample app is working fine with simulator but when using on Iphone i am getting below error 
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=application did not receive response from broker., MSALInternalErrorCodeKey=-42700, MSALCorrelationIDKey=AD39CE99-4C19-4826-B1B6-498F00F0C856}

FYI: I am using Authenticator

**Comment by jasonjoh** [comment]
Have a look at MSAL's iOS 13 info here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/iOS-13-and-macOS-10.15-support-in-MSAL

Per [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1109) you may need to add code into the scene delegate to handle MSAL response as documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#objective-c-2).
