### ISSUE TITLE
Bad Token Issue After Password Change 

### ISSUE THREAD

**Issue by navee4721** [microsoftgraph/msgraph-training-ios-objectivec#30]
so here are steps to reproduce the issue

1) First login into app interactively which gets both access token and refresh token
2) change the password and try to login
3) as change of password will revoke the refresh token , app is doing interactive login now to get new set of tokens
4) but when it is making call to get user info its giving error as below 

![image](https://user-images.githubusercontent.com/44012535/176537611-7e89b972-11c2-4f36-ac3e-496f0ad1ffdf.png)
5) based on error i am doing signout and trying to login again but still i am seeing same error

**Comment by navee4721** [comment]
Additional info this error will disappear after couple of sign in tries and it works fine till i change my password nexttime

**Comment by jasonjoh** [comment]
I see you also commented on https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1212. It sounds like there's an issue with how MSAL is caching refresh tokens. There is a comment in that thread that removing the account seemed to fix their issue. The `signOut` method is calling `removeAccount`, but you said that didn't clear the error.

I wonder if setting the `promptType` property on `interactiveParameters` to `MSALPromptTypeConsent` would help? That should force a re-consent (prompt with requested permission scopes).
